---
name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp-vsn: ['22.3', '23', '24']
    container: erlang:${{ matrix.otp-vsn }}-alpine
    steps:
      - uses: actions/checkout@v2
      - run: apk add git
      - run: rebar3 lint
      - run: rebar3 dialyzer
      - run: rebar3 do ct --cover, cover --verbose
